/**
THIS FILE WAS GENERATED AUTOMATICALLY
IF YOU WANT TO ALTER IT MAKE CHANGES TO codegen.py
**/

#pragma once

#define CMD_HALT_NAME "halt"
#define CMD_CALL_NAME "call"
#define CMD_RETURN_NAME "return"
#define CMD_JUMP_NAME "jump"
#define CMD_JUMPT_NAME "jumpt"
#define CMD_JUMPF_NAME "jumpf"
#define CMD_PUSH_NAME "push"
#define CMD_PUSHI_NAME "pushi"
#define CMD_PUSHU_NAME "pushu"
#define CMD_PUSHF_NAME "pushf"
#define CMD_POP_NAME "pop"
#define CMD_POPS_NAME "pops"
#define CMD_TOP_NAME "top"
#define CMD_EQI_NAME "eqi"
#define CMD_EQU_NAME "equ"
#define CMD_EQF_NAME "eqf"
#define CMD_NEI_NAME "nei"
#define CMD_NEU_NAME "neu"
#define CMD_NEF_NAME "nef"
#define CMD_LI_NAME "li"
#define CMD_LU_NAME "lu"
#define CMD_LF_NAME "lf"
#define CMD_LEI_NAME "lei"
#define CMD_LEU_NAME "leu"
#define CMD_LEF_NAME "lef"
#define CMD_GI_NAME "gi"
#define CMD_GU_NAME "gu"
#define CMD_GF_NAME "gf"
#define CMD_GEI_NAME "gei"
#define CMD_GEU_NAME "geu"
#define CMD_GEF_NAME "gef"
#define CMD_BAND_NAME "band"
#define CMD_AND_NAME "and"
#define CMD_BOR_NAME "bor"
#define CMD_OR_NAME "or"
#define CMD_BXOR_NAME "bxor"
#define CMD_BNOT_NAME "bnot"
#define CMD_NOT_NAME "not"
#define CMD_LS_NAME "ls"
#define CMD_RS_NAME "rs"
#define CMD_LRS_NAME "lrs"
#define CMD_ADDI_NAME "addi"
#define CMD_ADDU_NAME "addu"
#define CMD_ADDF_NAME "addf"
#define CMD_SUBI_NAME "subi"
#define CMD_SUBU_NAME "subu"
#define CMD_SUBF_NAME "subf"
#define CMD_MULI_NAME "muli"
#define CMD_MULU_NAME "mulu"
#define CMD_MULF_NAME "mulf"
#define CMD_DIVI_NAME "divi"
#define CMD_DIVU_NAME "divu"
#define CMD_DIVF_NAME "divf"
#define CMD_MODI_NAME "modi"
#define CMD_MODU_NAME "modu"
#define CMD_SQRT_NAME "sqrt"
#define CMD_PRINTI_NAME "printi"
#define CMD_PRINTU_NAME "printu"
#define CMD_PRINTF_NAME "printf"
#define CMD_SCANI_NAME "scani"
#define CMD_SCANU_NAME "scanu"
#define CMD_SCANF_NAME "scanf"
#define CMD_LOAD_NAME "load"
#define CMD_STORE_NAME "store"
#define CMD_MOVE_NAME "move"