#pragma once

#define CMD_HALT_NAME "halt"

#define CMD_CALL_NAME "call"
#define CMD_RETURN_NAME "return"

#define CMD_JUMP_NAME "jump"
#define CMD_JUMPEQ_NAME "jumpeq"
#define CMD_JUMPNE_NAME "jumpne"
#define CMD_JUMPL_NAME "jumpl"
#define CMD_JUMPLE_NAME "jumple"
#define CMD_JUMPG_NAME "jumpg"
#define CMD_JUMPGE_NAME "jumpge"

#define CMD_PUSHB_NAME "pushb"
#define CMD_PUSHQ_NAME "pushq"
#define CMD_PUSHH_NAME "pushh"
#define CMD_PUSHW_NAME "pushw"
#define CMD_PUSHCHAR_NAME "pushc"
#define CMD_PUSHSHRT_NAME "pushs"
#define CMD_PUSHINT_NAME "pushi"
#define CMD_PUSHLONG_NAME "pushl"
#define CMD_PUSHUCHAR_NAME "pushuc"
#define CMD_PUSHUSHRT_NAME "pushus"
#define CMD_PUSHUINT_NAME "pushui"
#define CMD_PUSHULONG_NAME "pushul"
#define CMD_PUSHFLT_NAME "pushf"
#define CMD_PUSHDBL_NAME "pushd"

#define CMD_POPB_NAME "popb"
#define CMD_POPQ_NAME "popq"
#define CMD_POPH_NAME "poph"
#define CMD_POPW_NAME "popw"
#define CMD_POPSTK_NAME "popstk"

#define CMD_TOPB_NAME "topb"
#define CMD_TOPQ_NAME "topq"
#define CMD_TOPH_NAME "toph"
#define CMD_TOPW_NAME "topw"

#define CMD_CMPCHAR_NAME "cmpc"
#define CMD_CMPSHRT_NAME "cmps"
#define CMD_CMPINT_NAME "cmpi"
#define CMD_CMPLONG_NAME "cmpl"
#define CMD_CMPUCHAR_NAME "cmpuc"
#define CMD_CMPUSHRT_NAME "cmpus"
#define CMD_CMPUINT_NAME "cmpui"
#define CMD_CMPULONG_NAME "cmpul"
#define CMD_CMPFLT_NAME "cmpf"
#define CMD_CMPDBL_NAME "cmpd"

#define CMD_ADDCHAR_NAME "addc"
#define CMD_ADDSHRT_NAME "adds"
#define CMD_ADDINT_NAME "addi"
#define CMD_ADDLONG_NAME "addl"
#define CMD_ADDUCHAR_NAME "adduc"
#define CMD_ADDUSHRT_NAME "addus"
#define CMD_ADDUINT_NAME "addui"
#define CMD_ADDULONG_NAME "addul"
#define CMD_ADDFLT_NAME "addf"
#define CMD_ADDDBL_NAME "addd"

#define CMD_SUBCHAR_NAME "subc"
#define CMD_SUBSHRT_NAME "subs"
#define CMD_SUBINT_NAME "subi"
#define CMD_SUBLONG_NAME "subl"
#define CMD_SUBUCHAR_NAME "subuc"
#define CMD_SUBUSHRT_NAME "subus"
#define CMD_SUBUINT_NAME "subui"
#define CMD_SUBULONG_NAME "subul"
#define CMD_SUBFLT_NAME "subf"
#define CMD_SUBDBL_NAME "subd"

#define CMD_MULCHAR_NAME "mulc"
#define CMD_MULSHRT_NAME "muls"
#define CMD_MULINT_NAME "muli"
#define CMD_MULLONG_NAME "mull"
#define CMD_MULUCHAR_NAME "muluc"
#define CMD_MULUSHRT_NAME "mulus"
#define CMD_MULUINT_NAME "mului"
#define CMD_MULULONG_NAME "mulul"
#define CMD_MULFLT_NAME "mulf"
#define CMD_MULDBL_NAME "muld"

#define CMD_DIVCHAR_NAME "divc"
#define CMD_DIVSHRT_NAME "divs"
#define CMD_DIVINT_NAME "divi"
#define CMD_DIVLONG_NAME "divl"
#define CMD_DIVUCHAR_NAME "divuc"
#define CMD_DIVUSHRT_NAME "divus"
#define CMD_DIVUINT_NAME "divui"
#define CMD_DIVULONG_NAME "divul"
#define CMD_DIVFLT_NAME "divf"
#define CMD_DIVDBL_NAME "divd"

#define CMD_MODCHAR_NAME "modc"
#define CMD_MODSHRT_NAME "mods"
#define CMD_MODINT_NAME "modi"
#define CMD_MODLONG_NAME "modl"
#define CMD_MODUCHAR_NAME "moduc"
#define CMD_MODUSHRT_NAME "modus"
#define CMD_MODUINT_NAME "modui"
#define CMD_MODULONG_NAME "modul"

#define CMD_SQRTFLT_NAME "sqrtf"
#define CMD_SQRTDBL_NAME "sqrtd"

#define CMD_SCANCHAR_NAME "scanc"
#define CMD_SCANSHRT_NAME "scans"
#define CMD_SCANINT_NAME "scani"
#define CMD_SCANLONG_NAME "scanl"
#define CMD_SCANUCHAR_NAME "scanuc"
#define CMD_SCANUSHRT_NAME "scanus"
#define CMD_SCANUINT_NAME "scanui"
#define CMD_SCANULONG_NAME "scanul"
#define CMD_SCANFLT_NAME "scanf"
#define CMD_SCANDBL_NAME "scand"

#define CMD_PRINTCHAR_NAME "printc"
#define CMD_PRINTSHRT_NAME "prints"
#define CMD_PRINTINT_NAME "printi"
#define CMD_PRINTLONG_NAME "printl"
#define CMD_PRINTUCHAR_NAME "printuc"
#define CMD_PRINTUSHRT_NAME "printus"
#define CMD_PRINTUINT_NAME "printui"
#define CMD_PRINTULONG_NAME "printul"
#define CMD_PRINTFLT_NAME "printf"
#define CMD_PRINTDBL_NAME "printd"

#define CMD_STOREWR_NAME "storewr"

#define CMD_LOADWR_NAME "loadwr"
