#pragma once

#define REG_NAME_RA "ra"
#define REG_NAME_RB "rb"
#define REG_NAME_RC "rc"
#define REG_NAME_RD "rd"
#define REG_NAME_RE "re"
#define REG_NAME_RF "rf"
#define REG_NAME_RG "rg"
#define REG_NAME_RH "rh"
#define REG_NAME_RI "ri"
#define REG_NAME_RJ "rj"
#define REG_NAME_RK "rk"
#define REG_NAME_RL "rl"
#define REG_NAME_RM "rm"
#define REG_NAME_RN "rn"
#define REG_NAME_RO "ro"
#define REG_NAME_RP "rp"
